### ISSUE TITLE
Zephyrのcbindingを作る

### ISSUE THREAD

**Issue by tomoyuki-nakabayashi** [tomoyuki-nakabayashi/zephyr-rust-integration#1]
printkを使いたいな。

**Comment by tomoyuki-nakabayashi** [comment]
```
$ cargo install bindgen
```

一回サンプルアプリケーションをビルドすると、必要なマクロ定義が得られる。

`|> build/zephyr/include/generated/autoconf.h`

bindingsを作る。

```
$ cd zephyr/include
$ cat bindings.h
#include "../samples/net/rust_echo_server/build/zephyr/include/generated/autoconf.h"
#include "zephyr.h"

$ bindgen bindings.h -o bindings.rs -- -I./ -I../arch/arm/include -I../samples/net/rust_echo_server/build/zephyr/include/generated
```

カレントディレクトリと、arch用のincludeディレクトリへのパスを追加する。

**Comment by tomoyuki-nakabayashi** [comment]
`--ctypes-prefix cty`を付けないと、stdの型定義が使われてしまう。

```
bindgen --use-core --ctypes-prefix cty bindings.h -o bindings.rs -- -I./ -I../arch/arm/include -I../samples/net/rust_echo_server/build/zephyr/include/generated
```

**Comment by tomoyuki-nakabayashi** [comment]
networkをやってみる。

```
$ bindgen --use-core --ctypes-prefix cty rust_bindings.h -o bindings.rs -- -I./ -I../arch/arm/include -I../samples/rust/echo_server/build/zephyr/include/generated
...
./logging/log_msg.h:151:1: error: static_assert failed due to requirement 'sizeof(union log_msg_head_data) == sizeof(struct log_msg_ext_head_data)' "Structure must be same size", err: true
./logging/log_core.h:19:2: error: "Logger does not support 64 bit architecture.", err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

うーん。

**Comment by tomoyuki-nakabayashi** [comment]
```
$ bindgen rust_bindings.h -o bindings.rs -- -I./ -I../arch/arm/include -I../samples/net/rust_echo_server/build/zephyr/include/generated
./syscall.h:11:10: fatal error: 'syscall_list.h' file not found
./syscall.h:11:10: fatal error: 'syscall_list.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

1回ninja buildしないと、上のエラーになるのもしんどいな。

**Comment by tomoyuki-nakabayashi** [comment]
```
$ bindgen --use-core --ctypes-prefix cty rust_bindings.h -o bindings.rs -- -I./ -I../arch/arm/include -I../samples/rust/echo_server/build/zephyr/include/generated -m32
```

なるほどね…。これならいいのね。

**Comment by tomoyuki-nakabayashi** [comment]
その方がだいぶスマートかな。

```console
$ cat 
$ cat bindings/headers/kernel_bindings.h 
#include <autoconf.h>
#include <kernel.h>
```

```console
$ bindgen --use-core --ctypes-prefix cty bindings/headers/kernel_bindings.h -o bindings/src/kernel.rs -- -I${ZEPHYR_BASE}/include -I${ZEPHYR_BASE}/arch/arm/include -I./build/zephyr/include/generated -m32
```

**Comment by tomoyuki-nakabayashi** [comment]
Zephyrの持っているstdioのbindings。

```
$ bindgen --use-core --ctypes-prefix cty bindings/headers/stdio_bindings
.h -o bindings/src/stdio.rs -- -I${ZEPHYR_BASE}/include -I${ZEPHYR_BASE}/lib/libc/minimal/include -I${ZEPHYR_BASE}/arch/arm/include -I./build/zephyr/include/generated -m32
```

**Comment by tomoyuki-nakabayashi** [comment]
POSIX APIとしてbindを作りたいが、inline関数がマクロ展開した後の最終的なAPIでbindingが作られてしまう。
もう少し細かい制御をせねばならぬ。

**Comment by tomoyuki-nakabayashi** [comment]
```console
$ bindgen --use-core --ctypes-prefix cty bindings/headers/bindings.h -o bindings/src/test.rs --whitelist-function "printf" -- -I${ZEPHYR_BASE}/include -I${ZEPHYR_BASE}/lib/libc/minimal/include -I${ZEPHYR_BASE}/arch/arm/include -I./build/zephyr/include/generated -m32

$ cat bindings/src/test.rs
/* automatically generated by rust-bindgen */

extern "C" {
    pub fn printf(fmt: *const cty::c_char, ...) -> cty::c_int;
}
```

なるほどねぇ～。

**Comment by tomoyuki-nakabayashi** [comment]
```
$ bindgen --use-core --ctypes-prefix cty bindings/headers/bindings.h -o bindings/src/test.rs --whitelist-function "socket" -- -I${ZEPHYR_BASE}/include -I${ZEPHYR_BASE}/lib/libc/minimal/include -I${ZEPHYR_BASE}/arch/arm/include -I./build/zephyr/include/generated -m32
/home/tomoyuki/work/05.nrf52840/my_fork_zephyr/lib/libc/minimal/include/string.h:38:15: warning: incompatible redeclaration of library function 'memchr' [-Wincompatible-library-redeclaration], err: false
[2019-02-25T00:58:36Z ERROR bindgen::ir::context] unused option: --whitelist-function socket
```

ぬ…。inlineだから扱いが違うんかなぁ…。
